/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudokuprojekt;

import java.awt.Color;
import static java.awt.image.ImageObserver.HEIGHT;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Sudoku9x9 extends javax.swing.JFrame {
    private ArrayList<JTextField> al = new ArrayList<JTextField>();
    private int hours;
    private int minutes;
    private int seconds;
    private boolean state=false;
    private boolean flag=false;
    Connection polaczenie = null;

    /**
     * Creates new form SystemDziesietnyLatwy
     */
    public Sudoku9x9() {
        initComponents();
        try{
            polaczenie = DriverManager.getConnection(OknoLogowania.CONN_STRING,OknoLogowania.USERNAME,OknoLogowania.PASSWORD);
            System.out.println("Polaczyles sie z baza");
        }catch(SQLException e){
            System.out.println("Cos poszlo nie tak "+ e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cell1 = new javax.swing.JTextField();
        cell2 = new javax.swing.JTextField();
        cell3 = new javax.swing.JTextField();
        cell19 = new javax.swing.JTextField();
        cell21 = new javax.swing.JTextField();
        cell11 = new javax.swing.JTextField();
        cell20 = new javax.swing.JTextField();
        cell12 = new javax.swing.JTextField();
        cell10 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cell6 = new javax.swing.JTextField();
        cell22 = new javax.swing.JTextField();
        cell5 = new javax.swing.JTextField();
        cell4 = new javax.swing.JTextField();
        cell24 = new javax.swing.JTextField();
        cell14 = new javax.swing.JTextField();
        cell23 = new javax.swing.JTextField();
        cell15 = new javax.swing.JTextField();
        cell13 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cell9 = new javax.swing.JTextField();
        cell25 = new javax.swing.JTextField();
        cell8 = new javax.swing.JTextField();
        cell7 = new javax.swing.JTextField();
        cell27 = new javax.swing.JTextField();
        cell17 = new javax.swing.JTextField();
        cell26 = new javax.swing.JTextField();
        cell18 = new javax.swing.JTextField();
        cell16 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        cell33 = new javax.swing.JTextField();
        cell49 = new javax.swing.JTextField();
        cell32 = new javax.swing.JTextField();
        cell31 = new javax.swing.JTextField();
        cell51 = new javax.swing.JTextField();
        cell41 = new javax.swing.JTextField();
        cell50 = new javax.swing.JTextField();
        cell42 = new javax.swing.JTextField();
        cell40 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        cell30 = new javax.swing.JTextField();
        cell46 = new javax.swing.JTextField();
        cell29 = new javax.swing.JTextField();
        cell28 = new javax.swing.JTextField();
        cell48 = new javax.swing.JTextField();
        cell38 = new javax.swing.JTextField();
        cell47 = new javax.swing.JTextField();
        cell39 = new javax.swing.JTextField();
        cell37 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        cell36 = new javax.swing.JTextField();
        cell52 = new javax.swing.JTextField();
        cell35 = new javax.swing.JTextField();
        cell34 = new javax.swing.JTextField();
        cell54 = new javax.swing.JTextField();
        cell44 = new javax.swing.JTextField();
        cell53 = new javax.swing.JTextField();
        cell45 = new javax.swing.JTextField();
        cell43 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        cell63 = new javax.swing.JTextField();
        cell79 = new javax.swing.JTextField();
        cell62 = new javax.swing.JTextField();
        cell61 = new javax.swing.JTextField();
        cell81 = new javax.swing.JTextField();
        cell71 = new javax.swing.JTextField();
        cell80 = new javax.swing.JTextField();
        cell72 = new javax.swing.JTextField();
        cell70 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        cell60 = new javax.swing.JTextField();
        cell76 = new javax.swing.JTextField();
        cell59 = new javax.swing.JTextField();
        cell58 = new javax.swing.JTextField();
        cell78 = new javax.swing.JTextField();
        cell68 = new javax.swing.JTextField();
        cell77 = new javax.swing.JTextField();
        cell69 = new javax.swing.JTextField();
        cell67 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        cell57 = new javax.swing.JTextField();
        cell73 = new javax.swing.JTextField();
        cell56 = new javax.swing.JTextField();
        cell55 = new javax.swing.JTextField();
        cell75 = new javax.swing.JTextField();
        cell65 = new javax.swing.JTextField();
        cell74 = new javax.swing.JTextField();
        cell66 = new javax.swing.JTextField();
        cell64 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        hour = new javax.swing.JLabel();
        minute = new javax.swing.JLabel();
        second = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(850, 650));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 3));
        jPanel1.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanel1.setPreferredSize(new java.awt.Dimension(180, 180));
        jPanel1.setLayout(null);

        cell1.setBackground(new java.awt.Color(204, 204, 255));
        cell1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell1.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(cell1);
        cell1.setBounds(0, 0, 60, 60);

        cell2.setBackground(new java.awt.Color(204, 204, 255));
        cell2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell2.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(cell2);
        cell2.setBounds(60, 0, 60, 60);

        cell3.setBackground(new java.awt.Color(204, 204, 255));
        cell3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell3.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(cell3);
        cell3.setBounds(120, 0, 60, 60);

        cell19.setBackground(new java.awt.Color(204, 204, 255));
        cell19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell19.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(cell19);
        cell19.setBounds(0, 120, 60, 60);

        cell21.setBackground(new java.awt.Color(204, 204, 255));
        cell21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell21.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(cell21);
        cell21.setBounds(120, 120, 60, 60);

        cell11.setBackground(new java.awt.Color(204, 204, 255));
        cell11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell11.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(cell11);
        cell11.setBounds(60, 60, 60, 60);

        cell20.setBackground(new java.awt.Color(204, 204, 255));
        cell20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell20.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(cell20);
        cell20.setBounds(60, 120, 60, 60);

        cell12.setBackground(new java.awt.Color(204, 204, 255));
        cell12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell12.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(cell12);
        cell12.setBounds(120, 60, 60, 60);

        cell10.setBackground(new java.awt.Color(204, 204, 255));
        cell10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell10.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(cell10);
        cell10.setBounds(0, 60, 60, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 20, 180, 180);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 3));
        jPanel2.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanel2.setPreferredSize(new java.awt.Dimension(180, 180));
        jPanel2.setLayout(null);

        cell6.setBackground(new java.awt.Color(255, 204, 255));
        cell6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell6.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel2.add(cell6);
        cell6.setBounds(120, 0, 60, 60);

        cell22.setBackground(new java.awt.Color(255, 204, 255));
        cell22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell22.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel2.add(cell22);
        cell22.setBounds(0, 120, 60, 60);

        cell5.setBackground(new java.awt.Color(255, 204, 255));
        cell5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell5.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel2.add(cell5);
        cell5.setBounds(60, 0, 60, 60);

        cell4.setBackground(new java.awt.Color(255, 204, 255));
        cell4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell4.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel2.add(cell4);
        cell4.setBounds(0, 0, 60, 60);

        cell24.setBackground(new java.awt.Color(255, 204, 255));
        cell24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell24.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel2.add(cell24);
        cell24.setBounds(120, 120, 60, 60);

        cell14.setBackground(new java.awt.Color(255, 204, 255));
        cell14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell14.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel2.add(cell14);
        cell14.setBounds(60, 60, 60, 60);

        cell23.setBackground(new java.awt.Color(255, 204, 255));
        cell23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell23.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel2.add(cell23);
        cell23.setBounds(60, 120, 60, 60);

        cell15.setBackground(new java.awt.Color(255, 204, 255));
        cell15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell15.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel2.add(cell15);
        cell15.setBounds(120, 60, 60, 60);

        cell13.setBackground(new java.awt.Color(255, 204, 255));
        cell13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell13.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel2.add(cell13);
        cell13.setBounds(0, 60, 60, 60);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(200, 20, 180, 180);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 3));
        jPanel3.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanel3.setPreferredSize(new java.awt.Dimension(180, 180));
        jPanel3.setLayout(null);

        cell9.setBackground(new java.awt.Color(204, 204, 255));
        cell9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell9.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel3.add(cell9);
        cell9.setBounds(120, 0, 60, 60);

        cell25.setBackground(new java.awt.Color(204, 204, 255));
        cell25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell25.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel3.add(cell25);
        cell25.setBounds(0, 120, 60, 60);

        cell8.setBackground(new java.awt.Color(204, 204, 255));
        cell8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell8.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel3.add(cell8);
        cell8.setBounds(60, 0, 60, 60);

        cell7.setBackground(new java.awt.Color(204, 204, 255));
        cell7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell7.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel3.add(cell7);
        cell7.setBounds(0, 0, 60, 60);

        cell27.setBackground(new java.awt.Color(204, 204, 255));
        cell27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell27.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel3.add(cell27);
        cell27.setBounds(120, 120, 60, 60);

        cell17.setBackground(new java.awt.Color(204, 204, 255));
        cell17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell17.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel3.add(cell17);
        cell17.setBounds(60, 60, 60, 60);

        cell26.setBackground(new java.awt.Color(204, 204, 255));
        cell26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell26.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel3.add(cell26);
        cell26.setBounds(60, 120, 60, 60);

        cell18.setBackground(new java.awt.Color(204, 204, 255));
        cell18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell18.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel3.add(cell18);
        cell18.setBounds(120, 60, 60, 60);

        cell16.setBackground(new java.awt.Color(204, 204, 255));
        cell16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell16.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel3.add(cell16);
        cell16.setBounds(0, 60, 60, 60);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(380, 20, 180, 180);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 3));
        jPanel5.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanel5.setPreferredSize(new java.awt.Dimension(180, 180));
        jPanel5.setLayout(null);

        cell33.setBackground(new java.awt.Color(204, 204, 255));
        cell33.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell33.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel5.add(cell33);
        cell33.setBounds(120, 0, 60, 60);

        cell49.setBackground(new java.awt.Color(204, 204, 255));
        cell49.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell49.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell49.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel5.add(cell49);
        cell49.setBounds(0, 120, 60, 60);

        cell32.setBackground(new java.awt.Color(204, 204, 255));
        cell32.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell32.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel5.add(cell32);
        cell32.setBounds(60, 0, 60, 60);

        cell31.setBackground(new java.awt.Color(204, 204, 255));
        cell31.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell31.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel5.add(cell31);
        cell31.setBounds(0, 0, 60, 60);

        cell51.setBackground(new java.awt.Color(204, 204, 255));
        cell51.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell51.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel5.add(cell51);
        cell51.setBounds(120, 120, 60, 60);

        cell41.setBackground(new java.awt.Color(204, 204, 255));
        cell41.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell41.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel5.add(cell41);
        cell41.setBounds(60, 60, 60, 60);

        cell50.setBackground(new java.awt.Color(204, 204, 255));
        cell50.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell50.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel5.add(cell50);
        cell50.setBounds(60, 120, 60, 60);

        cell42.setBackground(new java.awt.Color(204, 204, 255));
        cell42.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell42.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel5.add(cell42);
        cell42.setBounds(120, 60, 60, 60);

        cell40.setBackground(new java.awt.Color(204, 204, 255));
        cell40.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell40.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel5.add(cell40);
        cell40.setBounds(0, 60, 60, 60);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(200, 200, 180, 180);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 3));
        jPanel4.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanel4.setPreferredSize(new java.awt.Dimension(180, 180));
        jPanel4.setLayout(null);

        cell30.setBackground(new java.awt.Color(255, 204, 255));
        cell30.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell30.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel4.add(cell30);
        cell30.setBounds(120, 0, 60, 60);

        cell46.setBackground(new java.awt.Color(255, 204, 255));
        cell46.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell46.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel4.add(cell46);
        cell46.setBounds(0, 120, 60, 60);

        cell29.setBackground(new java.awt.Color(255, 204, 255));
        cell29.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell29.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel4.add(cell29);
        cell29.setBounds(60, 0, 60, 60);

        cell28.setBackground(new java.awt.Color(255, 204, 255));
        cell28.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell28.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel4.add(cell28);
        cell28.setBounds(0, 0, 60, 60);

        cell48.setBackground(new java.awt.Color(255, 204, 255));
        cell48.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell48.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel4.add(cell48);
        cell48.setBounds(120, 120, 60, 60);

        cell38.setBackground(new java.awt.Color(255, 204, 255));
        cell38.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell38.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel4.add(cell38);
        cell38.setBounds(60, 60, 60, 60);

        cell47.setBackground(new java.awt.Color(255, 204, 255));
        cell47.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell47.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel4.add(cell47);
        cell47.setBounds(60, 120, 60, 60);

        cell39.setBackground(new java.awt.Color(255, 204, 255));
        cell39.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell39.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell39.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel4.add(cell39);
        cell39.setBounds(120, 60, 60, 60);

        cell37.setBackground(new java.awt.Color(255, 204, 255));
        cell37.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell37.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel4.add(cell37);
        cell37.setBounds(0, 60, 60, 60);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(20, 200, 180, 180);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 3));
        jPanel6.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanel6.setPreferredSize(new java.awt.Dimension(180, 180));
        jPanel6.setLayout(null);

        cell36.setBackground(new java.awt.Color(255, 204, 255));
        cell36.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell36.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel6.add(cell36);
        cell36.setBounds(120, 0, 60, 60);

        cell52.setBackground(new java.awt.Color(255, 204, 255));
        cell52.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell52.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel6.add(cell52);
        cell52.setBounds(0, 120, 60, 60);

        cell35.setBackground(new java.awt.Color(255, 204, 255));
        cell35.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell35.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel6.add(cell35);
        cell35.setBounds(60, 0, 60, 60);

        cell34.setBackground(new java.awt.Color(255, 204, 255));
        cell34.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell34.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel6.add(cell34);
        cell34.setBounds(0, 0, 60, 60);

        cell54.setBackground(new java.awt.Color(255, 204, 255));
        cell54.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell54.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel6.add(cell54);
        cell54.setBounds(120, 120, 60, 60);

        cell44.setBackground(new java.awt.Color(255, 204, 255));
        cell44.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell44.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel6.add(cell44);
        cell44.setBounds(60, 60, 60, 60);

        cell53.setBackground(new java.awt.Color(255, 204, 255));
        cell53.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell53.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel6.add(cell53);
        cell53.setBounds(60, 120, 60, 60);

        cell45.setBackground(new java.awt.Color(255, 204, 255));
        cell45.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell45.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel6.add(cell45);
        cell45.setBounds(120, 60, 60, 60);

        cell43.setBackground(new java.awt.Color(255, 204, 255));
        cell43.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell43.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel6.add(cell43);
        cell43.setBounds(0, 60, 60, 60);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(380, 200, 180, 180);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 3));
        jPanel9.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanel9.setPreferredSize(new java.awt.Dimension(180, 180));
        jPanel9.setLayout(null);

        cell63.setBackground(new java.awt.Color(204, 204, 255));
        cell63.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell63.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell63.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel9.add(cell63);
        cell63.setBounds(120, 0, 60, 60);

        cell79.setBackground(new java.awt.Color(204, 204, 255));
        cell79.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell79.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell79.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell79.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel9.add(cell79);
        cell79.setBounds(0, 120, 60, 60);

        cell62.setBackground(new java.awt.Color(204, 204, 255));
        cell62.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell62.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell62.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel9.add(cell62);
        cell62.setBounds(60, 0, 60, 60);

        cell61.setBackground(new java.awt.Color(204, 204, 255));
        cell61.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell61.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell61.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel9.add(cell61);
        cell61.setBounds(0, 0, 60, 60);

        cell81.setBackground(new java.awt.Color(204, 204, 255));
        cell81.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell81.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell81.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell81.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel9.add(cell81);
        cell81.setBounds(120, 120, 60, 60);

        cell71.setBackground(new java.awt.Color(204, 204, 255));
        cell71.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell71.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell71.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell71.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel9.add(cell71);
        cell71.setBounds(60, 60, 60, 60);

        cell80.setBackground(new java.awt.Color(204, 204, 255));
        cell80.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell80.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell80.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell80.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel9.add(cell80);
        cell80.setBounds(60, 120, 60, 60);

        cell72.setBackground(new java.awt.Color(204, 204, 255));
        cell72.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell72.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell72.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell72.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel9.add(cell72);
        cell72.setBounds(120, 60, 60, 60);

        cell70.setBackground(new java.awt.Color(204, 204, 255));
        cell70.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell70.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell70.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell70.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel9.add(cell70);
        cell70.setBounds(0, 60, 60, 60);

        getContentPane().add(jPanel9);
        jPanel9.setBounds(380, 380, 180, 180);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 3));
        jPanel8.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanel8.setPreferredSize(new java.awt.Dimension(180, 180));
        jPanel8.setLayout(null);

        cell60.setBackground(new java.awt.Color(255, 204, 255));
        cell60.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell60.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell60.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel8.add(cell60);
        cell60.setBounds(120, 0, 60, 60);

        cell76.setBackground(new java.awt.Color(255, 204, 255));
        cell76.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell76.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell76.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell76.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel8.add(cell76);
        cell76.setBounds(0, 120, 60, 60);

        cell59.setBackground(new java.awt.Color(255, 204, 255));
        cell59.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell59.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell59.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell59.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel8.add(cell59);
        cell59.setBounds(60, 0, 60, 60);

        cell58.setBackground(new java.awt.Color(255, 204, 255));
        cell58.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell58.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell58.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell58.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel8.add(cell58);
        cell58.setBounds(0, 0, 60, 60);

        cell78.setBackground(new java.awt.Color(255, 204, 255));
        cell78.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell78.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell78.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell78.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel8.add(cell78);
        cell78.setBounds(120, 120, 60, 60);

        cell68.setBackground(new java.awt.Color(255, 204, 255));
        cell68.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell68.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell68.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell68.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel8.add(cell68);
        cell68.setBounds(60, 60, 60, 60);

        cell77.setBackground(new java.awt.Color(255, 204, 255));
        cell77.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell77.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell77.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell77.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel8.add(cell77);
        cell77.setBounds(60, 120, 60, 60);

        cell69.setBackground(new java.awt.Color(255, 204, 255));
        cell69.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell69.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell69.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell69.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel8.add(cell69);
        cell69.setBounds(120, 60, 60, 60);

        cell67.setBackground(new java.awt.Color(255, 204, 255));
        cell67.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell67.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell67.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell67.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel8.add(cell67);
        cell67.setBounds(0, 60, 60, 60);

        getContentPane().add(jPanel8);
        jPanel8.setBounds(200, 380, 180, 180);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102), 3));
        jPanel7.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanel7.setPreferredSize(new java.awt.Dimension(180, 180));
        jPanel7.setLayout(null);

        cell57.setBackground(new java.awt.Color(204, 204, 255));
        cell57.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell57.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell57.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel7.add(cell57);
        cell57.setBounds(120, 0, 60, 60);

        cell73.setBackground(new java.awt.Color(204, 204, 255));
        cell73.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell73.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell73.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell73.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel7.add(cell73);
        cell73.setBounds(0, 120, 60, 60);

        cell56.setBackground(new java.awt.Color(204, 204, 255));
        cell56.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell56.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell56.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel7.add(cell56);
        cell56.setBounds(60, 0, 60, 60);

        cell55.setBackground(new java.awt.Color(204, 204, 255));
        cell55.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell55.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel7.add(cell55);
        cell55.setBounds(0, 0, 60, 60);

        cell75.setBackground(new java.awt.Color(204, 204, 255));
        cell75.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell75.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell75.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell75.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel7.add(cell75);
        cell75.setBounds(120, 120, 60, 60);

        cell65.setBackground(new java.awt.Color(204, 204, 255));
        cell65.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell65.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell65.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell65.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel7.add(cell65);
        cell65.setBounds(60, 60, 60, 60);

        cell74.setBackground(new java.awt.Color(204, 204, 255));
        cell74.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell74.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell74.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell74.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel7.add(cell74);
        cell74.setBounds(60, 120, 60, 60);

        cell66.setBackground(new java.awt.Color(204, 204, 255));
        cell66.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell66.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell66.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel7.add(cell66);
        cell66.setBounds(120, 60, 60, 60);

        cell64.setBackground(new java.awt.Color(204, 204, 255));
        cell64.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cell64.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cell64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cell64.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel7.add(cell64);
        cell64.setBounds(0, 60, 60, 60);

        getContentPane().add(jPanel7);
        jPanel7.setBounds(20, 380, 180, 180);

        jButton1.setText("Generuj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(620, 120, 120, 23);

        jButton2.setText("Sprawdź");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(620, 160, 120, 23);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(570, 210, 280, 80);

        hour.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        hour.setText("00  :");
        getContentPane().add(hour);
        hour.setBounds(630, 60, 34, 14);

        minute.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        minute.setText("00  :");
        getContentPane().add(minute);
        minute.setBounds(670, 60, 28, 15);

        second.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        second.setText("00");
        getContentPane().add(second);
        second.setBounds(710, 60, 30, 15);

        jMenu1.setText("File");

        jMenuItem1.setText("Wybór Poziomu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Wyloguj się");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem3.setText("Tablica Rekordów");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        reset();
        state=true;
        if(!flag){
        Thread t=new Thread(){
            public void run(){
            for(;;){
            if(state==true){
                try {
                    TimeUnit.SECONDS.sleep(1);
                    if(seconds>60){
                    seconds=0;
                    minutes++;
                    }
                    if(minutes>60){
                    seconds=0;
                    minutes=0;
                    hours++;
                    }
                    second.setText(" : "+seconds);
                    seconds++;
                    minute.setText(" : "+minutes);
                    hour.setText(""+hours);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Sudoku9x9.class.getName()).log(Level.SEVERE, null, ex);
                }
            
            }
            else break;
            }
            }
            };
        t.start();
        flag=true;
        }
        jLabel1.setText("");
        if(SudokuProjekt.latwy==true){
        sudokuGenerator(9,3);
        }
        if(SudokuProjekt.sredni==true){
       sudokuGenerator(9,30);
        }
        if(SudokuProjekt.trudny==true){
        sudokuGenerator(9,45);
        }
         if(SudokuProjekt.latwybinarny==true){
       sudokuBinarnyGenerator(9,2);
        }
        if(SudokuProjekt.srednibinarny==true){
        sudokuBinarnyGenerator(9,30);
        }
        if(SudokuProjekt.trudnybinarny==true){
        sudokuBinarnyGenerator(9,45);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        SudokuProjekt.latwy=false;
        SudokuProjekt.sredni=false;
        SudokuProjekt.trudny=false;
        SudokuProjekt.latwybinarny=false;
        SudokuProjekt.srednibinarny=false;
        SudokuProjekt.trudnybinarny=false;
        WyborPoziomu frame2=new WyborPoziomu();
        frame2.setVisible(true);
        frame2.getContentPane().setBackground(new Color(219, 215, 217));
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        SudokuProjekt.latwy=false;
        SudokuProjekt.sredni=false;
        SudokuProjekt.trudny=false;
        SudokuProjekt.latwybinarny=false;
        SudokuProjekt.srednibinarny=false;
        SudokuProjekt.trudnybinarny=false;
        OknoLogowania frame2=new OknoLogowania();
        frame2.setVisible(true);
        frame2.getContentPane().setBackground(new Color(219, 215, 217));
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          if(SudokuProjekt.latwy || SudokuProjekt.sredni || SudokuProjekt.trudny) 
          {
              sprawdzDziesietny();
          }
          if(SudokuProjekt.latwybinarny || SudokuProjekt.srednibinarny || SudokuProjekt.trudnybinarny) 
          {
              sprawdzBinarny();
          }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        SudokuProjekt.latwy=false;
        SudokuProjekt.sredni=false;
        SudokuProjekt.trudny=false;
        SudokuProjekt.latwybinarny=false;
        SudokuProjekt.srednibinarny=false;
        SudokuProjekt.trudnybinarny=false;
        Wyniki frame2=new Wyniki();
        frame2.setVisible(true);
        frame2.getContentPane().setBackground(new Color(219, 215, 217));
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    
   private void sprawdzBinarny(){
    jLabel1.setText("");
       boolean czyDalej=true;
       boolean sprawdzwiersze=false;
       boolean sprawdzkolumny=false;
       boolean sprawdzBox=false;
        ArrayList<Integer> alcheck = new ArrayList<Integer>();
        if(al.isEmpty()){
        jLabel1.setText("Wygeneruj planszę!");
        jLabel1.setForeground(Color.red);
        czyDalej=false;
        }
        if(czyDalej==true){
        for (int i=0; i<al.size(); i++)
       {
          if("".equals(al.get(i).getText())){
              jLabel1.setText("Uzupełnij wszystkie pola");
              jLabel1.setForeground(Color.red);
          czyDalej=false;    
          break;
          }}}
        if(czyDalej==true){
        for (int i=0; i<al.size(); i++)
        {
            if (    al.get(i).getText().equals("0001")
                    || al.get(i).getText().equals("0010")
                    || al.get(i).getText().equals("0011")
                    || al.get(i).getText().equals("0100")
                    || al.get(i).getText().equals("0101")
                    || al.get(i).getText().equals("0110")
                    || al.get(i).getText().equals("0111")
                    || al.get(i).getText().equals("1000")
                    || al.get(i).getText().equals("1001")
                    ){
                continue;
            }else{
              jLabel1.setText("Uzupełnij pola wartościami od 0001 do 1001!");
              jLabel1.setForeground(Color.red);
              czyDalej=false;
              break;        }
        }}
        if(czyDalej==true){
            for(int i=0; i<al.size();i++){
            alcheck.add(Integer.parseInt(al.get(i).getText(),2));            
        }
            int wiersze=0;
            int kolumny=0;
            int tab[][]=new int[9][9];
          for (int i = 0;i< alcheck.size(); i++){
              if(i%9==0 && i!=0){
              wiersze++;
              kolumny=0;
              }
          tab[wiersze][kolumny]=alcheck.get(i);
          kolumny++;
          }  
         sprawdzwiersze=sprawdzWiersze(tab);
         sprawdzkolumny=sprawdzKolumny(tab);
         sprawdzBox=sprawdzBoxy(tab);
         if(sprawdzBox==true && sprawdzkolumny==true && sprawdzwiersze==true)
          {
              wyslijWynikDoBazy();
              state=false;
              flag=false;
              jLabel1.setText("Brawo! SUDOKU ROZWIĄZANE!!!");
              jLabel1.setForeground(Color.GREEN.darker().darker());
          }
          else{
              jLabel1.setText("SUDOKU ŹLE ROZWIĄZANE!");
              jLabel1.setForeground(Color.red);
          }      
        }
    }

   private void wyslijWynikDoBazy(){
       
       String godziny="",minuty="",sekundy="";
       String Czas = "";
       if(hours<10){
           Czas += "0"+hours;
           godziny = "0"+hours;
       }else{
           Czas += hours;
           godziny += hours;
       }
       if(minutes<10){
           Czas += "0"+minutes;
           minuty = "0"+minutes;
       }else{
           Czas += minutes;
           minuty += minutes;
       }
       if(seconds<10){
           Czas += "0"+seconds;
           sekundy="0"+seconds;
       }else{
           Czas += seconds;
           sekundy+=seconds;
       }
       
       int CzasInt = Integer.parseInt(Czas);
       String Poziom_trudnosci = "";
       String Rodzaj_planszy = "";
       
       if(SudokuProjekt.latwy){
            Poziom_trudnosci = "łatwy";
            Rodzaj_planszy = "dziesiętny";
       }else if(SudokuProjekt.sredni){
            Poziom_trudnosci = "średni";
            Rodzaj_planszy = "dziesiętny";
       }else if(SudokuProjekt.trudny){
            Poziom_trudnosci = "trudny";
            Rodzaj_planszy = "dziesiętny";
       }else if(SudokuProjekt.latwybinarny){
            Poziom_trudnosci = "łatwy";
            Rodzaj_planszy = "binarny";  
       }else if(SudokuProjekt.srednibinarny){
            Poziom_trudnosci = "średni";
            Rodzaj_planszy = "binarny"; 
       }else if(SudokuProjekt.trudnybinarny){
            Poziom_trudnosci = "trudny";
            Rodzaj_planszy = "binarny";
       }
       
            try{
                Statement zapytanie = (Statement)polaczenie.createStatement();
                String insert = "INSERT INTO wynik ( `Id_user`, `Poziom_trudnosci`, `Rodzaj_planszy`, `Czas`) VALUES ('"+OknoLogowania.sQLId_user+"', '"+Poziom_trudnosci+"', '"+Rodzaj_planszy+"', '"+Czas+"');";
                zapytanie.executeUpdate(insert);
                System.out.println("Dodano do bazy "+Poziom_trudnosci+" "+Rodzaj_planszy+" "+Czas);
                JOptionPane.showMessageDialog(null, " Przeszedłeś sudoku na poziomie "+Poziom_trudnosci+" w systemie "+Rodzaj_planszy+" z czasem równym: "+godziny+":"+minuty+":"+sekundy+" !", "Gratulacje !", HEIGHT);
            }catch(SQLException e){
                System.out.println("Cos poszlo nie tak "+ e);
            }
   }
   private void reset(){
   seconds=0;
        minutes=0;
        hours=0;
        second.setText(" : "+seconds);
        minute.setText(" : "+minutes);
        hour.setText(""+hours);}
   private void sprawdzDziesietny(){
    jLabel1.setText("");
       boolean czyDalej=true;
       boolean sprawdzwiersze=false;
       boolean sprawdzkolumny=false;
       boolean sprawdzBox=false;
        ArrayList<Integer> alcheck = new ArrayList<Integer>();
        if(al.isEmpty()){
        jLabel1.setText("Wygeneruj planszę!");
        jLabel1.setForeground(Color.red);
        czyDalej=false;
        }
        if(czyDalej==true){
        for (int i=0; i<al.size(); i++)
       {
          if("".equals(al.get(i).getText())){
              jLabel1.setText("Uzupełnij wszystkie pola");
              jLabel1.setForeground(Color.red);
          czyDalej=false;    
          break;
          }}}
        if(czyDalej==true){
        for (int i=0; i<al.size(); i++)
        {
            if (al.get(i).getText().matches("[1-9]+") && al.get(i).getText().length() < 2){
                continue;
            }else{
              jLabel1.setText("Uzupełnij pola wartościami od 1 do 9!");
              jLabel1.setForeground(Color.red);
              czyDalej=false;
              break;        }
        }}
        if(czyDalej==true){
            for(int i=0; i<al.size();i++){
            alcheck.add(Integer.parseInt(al.get(i).getText()));            
        }
            int wiersze=0;
            int kolumny=0;
            int tab[][]=new int[9][9];
          for (int i = 0;i< alcheck.size(); i++){
              if(i%9==0 && i!=0){
              wiersze++;
              kolumny=0;
              }
          tab[wiersze][kolumny]=alcheck.get(i);
          kolumny++;
          }  
         sprawdzwiersze=sprawdzWiersze(tab);
         sprawdzkolumny=sprawdzKolumny(tab);
         sprawdzBox=sprawdzBoxy(tab);
         if(sprawdzBox==true && sprawdzkolumny==true && sprawdzwiersze==true)
          {
              wyslijWynikDoBazy();
              state=false;
              flag=false;
              jLabel1.setText("Brawo! SUDOKU ROZWIĄZANE!!!");
              jLabel1.setForeground(Color.GREEN.darker().darker());
          }
          else{
              jLabel1.setText("SUDOKU ŹLE ROZWIĄZANE!");
              jLabel1.setForeground(Color.red);
          }      
        }
    }
    private boolean sprawdzWiersze(int[][] tab){
    boolean sprawdz=false;    
    Integer tabwiersze[]=new Integer[9];   
    for(int i=0; i<9; i++){
    for(int j=0; j<9; j++){
    tabwiersze[j]=tab[i][j];
    }
    if(areDistinct(tabwiersze)){
        sprawdz= true;
    }
    else {
    sprawdz= false;
    break;
    }
    }
        return sprawdz;
    }
    private boolean sprawdzKolumny(int[][] tab){
    boolean sprawdz=false; 
    int counter=0;
    Integer tabkolumny[]=new Integer[9]; 
    for(int il=0; il<9; il++){
    for(int i=0; i<9; i++){
    tabkolumny[i]=tab[i][counter];
    }
    counter++;
    if(areDistinct(tabkolumny)){
        sprawdz= true;
    }
    else {
    sprawdz= false;
    break;
    }
    }    
        return sprawdz;
    }
     private boolean sprawdzBoxy(int [][] tab){
        return (boxDuplikaty(0,3,0,3,tab) && boxDuplikaty(0,3,3,6,tab) && boxDuplikaty(0,3,6,9,tab) && boxDuplikaty(3,6,0,3,tab)
                && boxDuplikaty(3,6,3,6,tab) && boxDuplikaty(3,6,6,9,tab) && boxDuplikaty(6,9,0,3,tab) && boxDuplikaty(6,9,3,6,tab)
                && boxDuplikaty(6,9,6,9,tab));

    }
    private boolean boxDuplikaty(int rowStart, int rowFinish, int colStart, int colFinish, int [][]tab){
        HashSet<Integer> set = new HashSet<>();
        for (int i = rowStart; i < rowFinish  ; i++) {
            for (int j =colStart ; j < colFinish; j++) {
                set.add(tab[i][j]);
            }                        
        }
        if(set.size() != 9) return false;
        return true;
    }
      
    public static boolean areDistinct(Integer arr[]) 
    { 
       
        Set<Integer> s =  
           new HashSet<Integer>(Arrays.asList(arr)); 
   
        return (s.size() == arr.length); 
    } 
    private void sudokuGenerator(int N, int K){
        ArrayList<Integer> almatrix = new ArrayList<Integer>();
        al=addToArrayList();
        //czyszczenie sudoku w razie gdyby ktoś chciał wygenerować jeszcze raz
        for(int i=0; i<al.size(); i++){
        al.get(i).setText("");
        al.get(i).setEditable(true);
        al.get(i).setForeground(Color.BLACK);
        }
        
        int matrix[][];
        SudokuSolver sudoku = new SudokuSolver(N, K); 
        sudoku.fillValues(); 
        matrix=sudoku.returnSudoku();
        for (int i = 0; i<N; i++) 
        { 
            for (int j = 0; j<N; j++) 
                System.out.print(matrix[i][j] + " "); 
            System.out.println(); 
        } 
        System.out.println(); 
        for (int i = 0; i<N; i++) 
        { 
            for (int j = 0; j<N; j++) 
                almatrix.add(matrix[i][j]);
         } 
        for (int i=0; i<almatrix.size(); i++){
            if(almatrix.get(i)!=0){
                al.get(i).setText(Integer.toString(almatrix.get(i)));
                al.get(i).setForeground(new Color(36, 168, 102));
                al.get(i).setEditable(false);
                        }
        }
    }
    private void sudokuBinarnyGenerator(int N, int K){       
        ArrayList<Integer> almatrix = new ArrayList<Integer>();
        al=addToArrayList();
        //czyszczenie sudoku w razie gdyby ktoś chciał wygenerować jeszcze raz
        for(int i=0; i<al.size(); i++){
        al.get(i).setText("");
        al.get(i).setEditable(true);
        al.get(i).setForeground(Color.BLACK);
        }
        
        int matrix[][];
        SudokuSolver sudoku = new SudokuSolver(N, K); 
        sudoku.fillValues(); 
        matrix=sudoku.returnSudoku();
        for (int i = 0; i<N; i++) 
        { 
            for (int j = 0; j<N; j++) 
                System.out.print(matrix[i][j] + " "); 
            System.out.println(); 
        } 
        System.out.println(); 
        for (int i = 0; i<N; i++) 
        { 
            for (int j = 0; j<N; j++) 
                almatrix.add(matrix[i][j]);
         } 
        for (int i=0; i<almatrix.size(); i++){
            if(almatrix.get(i)!=0){
                switch(almatrix.get(i)){
                    case 1: al.get(i).setText("0001");
                    break;
                    case 2: al.get(i).setText("0010");
                    break;
                    case 3: al.get(i).setText("0011");
                    break;
                    case 4: al.get(i).setText("0100");
                    break;
                    case 5: al.get(i).setText("0101");
                    break;
                    case 6: al.get(i).setText("0110");
                    break;
                    case 7: al.get(i).setText("0111");
                    break;
                    case 8: al.get(i).setText("1000");
                    break;
                    case 9: al.get(i).setText("1001");
                    break;
                    
                }
                al.get(i).setForeground(new Color(36, 168, 102));
                al.get(i).setEditable(false);
                        }
        }
    }
    private ArrayList<JTextField> addToArrayList(){
    ArrayList<JTextField> al = new ArrayList<JTextField>();
    al.add(cell1);
    al.add(cell2);
    al.add(cell3);
    al.add(cell4);
    al.add(cell5);
    al.add(cell6);
    al.add(cell7);
    al.add(cell8);
    al.add(cell9);
    al.add(cell10);
    al.add(cell11);
    al.add(cell12);
    al.add(cell13);
    al.add(cell14);
    al.add(cell15);
    al.add(cell16);
    al.add(cell17);
    al.add(cell18);
    al.add(cell19);
    al.add(cell20);
    al.add(cell21);
    al.add(cell22);
    al.add(cell23);
    al.add(cell24);
    al.add(cell25);
    al.add(cell26);
    al.add(cell27);
    al.add(cell28);
    al.add(cell29);
    al.add(cell30);
    al.add(cell31);
    al.add(cell32);
    al.add(cell33);
    al.add(cell34);
    al.add(cell35);
    al.add(cell36);
    al.add(cell37);
    al.add(cell38);
    al.add(cell39);
    al.add(cell40);
    al.add(cell41);
    al.add(cell42);
    al.add(cell43);
    al.add(cell44);
    al.add(cell45);
    al.add(cell46);
    al.add(cell47);
    al.add(cell48);
    al.add(cell49);
    al.add(cell50);
    al.add(cell51);
    al.add(cell52);
    al.add(cell53);
    al.add(cell54);
    al.add(cell55);
    al.add(cell56);
    al.add(cell57);
    al.add(cell58);
    al.add(cell59);
    al.add(cell60);
    al.add(cell61);
    al.add(cell62);
    al.add(cell63);
    al.add(cell64);
    al.add(cell65);
    al.add(cell66);
    al.add(cell67);
    al.add(cell68);
    al.add(cell69);
    al.add(cell70);
    al.add(cell71);
    al.add(cell72);
    al.add(cell73);
    al.add(cell74);
    al.add(cell75);
    al.add(cell76);
    al.add(cell77);
    al.add(cell78);
    al.add(cell79);
    al.add(cell80);
    al.add(cell81);
    return al;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sudoku9x9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sudoku9x9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sudoku9x9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sudoku9x9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sudoku9x9().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cell1;
    private javax.swing.JTextField cell10;
    private javax.swing.JTextField cell11;
    private javax.swing.JTextField cell12;
    private javax.swing.JTextField cell13;
    private javax.swing.JTextField cell14;
    private javax.swing.JTextField cell15;
    private javax.swing.JTextField cell16;
    private javax.swing.JTextField cell17;
    private javax.swing.JTextField cell18;
    private javax.swing.JTextField cell19;
    private javax.swing.JTextField cell2;
    private javax.swing.JTextField cell20;
    private javax.swing.JTextField cell21;
    private javax.swing.JTextField cell22;
    private javax.swing.JTextField cell23;
    private javax.swing.JTextField cell24;
    private javax.swing.JTextField cell25;
    private javax.swing.JTextField cell26;
    private javax.swing.JTextField cell27;
    private javax.swing.JTextField cell28;
    private javax.swing.JTextField cell29;
    private javax.swing.JTextField cell3;
    private javax.swing.JTextField cell30;
    private javax.swing.JTextField cell31;
    private javax.swing.JTextField cell32;
    private javax.swing.JTextField cell33;
    private javax.swing.JTextField cell34;
    private javax.swing.JTextField cell35;
    private javax.swing.JTextField cell36;
    private javax.swing.JTextField cell37;
    private javax.swing.JTextField cell38;
    private javax.swing.JTextField cell39;
    private javax.swing.JTextField cell4;
    private javax.swing.JTextField cell40;
    private javax.swing.JTextField cell41;
    private javax.swing.JTextField cell42;
    private javax.swing.JTextField cell43;
    private javax.swing.JTextField cell44;
    private javax.swing.JTextField cell45;
    private javax.swing.JTextField cell46;
    private javax.swing.JTextField cell47;
    private javax.swing.JTextField cell48;
    private javax.swing.JTextField cell49;
    private javax.swing.JTextField cell5;
    private javax.swing.JTextField cell50;
    private javax.swing.JTextField cell51;
    private javax.swing.JTextField cell52;
    private javax.swing.JTextField cell53;
    private javax.swing.JTextField cell54;
    private javax.swing.JTextField cell55;
    private javax.swing.JTextField cell56;
    private javax.swing.JTextField cell57;
    private javax.swing.JTextField cell58;
    private javax.swing.JTextField cell59;
    private javax.swing.JTextField cell6;
    private javax.swing.JTextField cell60;
    private javax.swing.JTextField cell61;
    private javax.swing.JTextField cell62;
    private javax.swing.JTextField cell63;
    private javax.swing.JTextField cell64;
    private javax.swing.JTextField cell65;
    private javax.swing.JTextField cell66;
    private javax.swing.JTextField cell67;
    private javax.swing.JTextField cell68;
    private javax.swing.JTextField cell69;
    private javax.swing.JTextField cell7;
    private javax.swing.JTextField cell70;
    private javax.swing.JTextField cell71;
    private javax.swing.JTextField cell72;
    private javax.swing.JTextField cell73;
    private javax.swing.JTextField cell74;
    private javax.swing.JTextField cell75;
    private javax.swing.JTextField cell76;
    private javax.swing.JTextField cell77;
    private javax.swing.JTextField cell78;
    private javax.swing.JTextField cell79;
    private javax.swing.JTextField cell8;
    private javax.swing.JTextField cell80;
    private javax.swing.JTextField cell81;
    private javax.swing.JTextField cell9;
    private javax.swing.JLabel hour;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel minute;
    private javax.swing.JLabel second;
    // End of variables declaration//GEN-END:variables
}
